name: Deploy Pipeline

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: nikolasil/iliopoulosrent-frontend
  CONTAINER_NAME: iliopoulosrent-frontend
  NEXTAUTH_URL: https://iliopoulosrent.com
  NEXT_PUBLIC_SITE_URL: https://iliopoulosrent.com
  SHORT_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    name: 🏗️ Build and Push Docker Image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/arm64/v8 \
            --file Dockerfile \
            --tag $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:${SHORT_SHA::7} \
            --push .

  deploy:
    name: ⚙️ Deploy to EC2
    runs-on: ubuntu-22.04
    needs: build-and-push

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 44.200.151.12
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -eo pipefail

            IMAGE_TAG=${SHORT_SHA::7}
            CONTAINER_NAME=${{ env.CONTAINER_NAME }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}

            echo "Pulling new image..."
            sudo docker pull $IMAGE_NAME:$IMAGE_TAG

            echo "Stopping current container if running..."
            sudo docker rm -f $CONTAINER_NAME || true

            echo "Starting new container..."
            if ! sudo docker run -d \
              --name $CONTAINER_NAME \
              -e NEXTAUTH_URL=${{ env.NEXTAUTH_URL }} \
              -e NEXT_PUBLIC_SITE_URL=${{ env.NEXT_PUBLIC_SITE_URL }} \
              -p 8081:3000 \
              $IMAGE_NAME:$IMAGE_TAG; then

              echo "❌ Failed to start new container. Rolling back to 'latest'..."
              sudo docker pull $IMAGE_NAME:latest
              sudo docker rm -f $CONTAINER_NAME || true
              sudo docker run -d \
                --name $CONTAINER_NAME \
                -e NEXTAUTH_URL=${{ env.NEXTAUTH_URL }} \
                -e NEXT_PUBLIC_SITE_URL=${{ env.NEXT_PUBLIC_SITE_URL }} \
                -p 8081:3000 \
                $IMAGE_NAME:latest
            fi
