name: Deploy Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker buildx build --platform linux/arm64/v8 . --load --file Dockerfile --tag nikolasil/iliopoulosrent-frontend:latest
      - name: Push Docker image to Docker Hub
        run: docker push nikolasil/iliopoulosrent-frontend:latest
      - name: Connect to ec2 instance and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 44.200.151.12
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop iliopoulosrent-frontend || true
            sudo docker rm iliopoulosrent-frontend || true
            sudo docker pull nikolasil/iliopoulosrent-frontend || true
            sudo docker run -d --name iliopoulosrent-frontend -e NEXTAUTH_URL=https://iliopoulosrent.com -e NEXT_PUBLIC_SITE_URL=https://iliopoulosrent.com -p 8081:3000 nikolasil/iliopoulosrent-frontend:latest